### ISSUE TITLE
Copy support

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/ports-of-call#20]
@cmauney brought up that there is some raw Kokkos in spiner for the `GetOnDevice()` call. Could that sort of copy behavior be wrapped in `ports-of-call` instead so that there's a Kokkos version and a Cuda version?

Tagging @Yurlungur @chadmeyer @dholladay00 as well

**Comment by mauneyc-LANL** [comment]
Connecting to https://github.com/lanl/spiner/issues/54

**Comment by Yurlungur** [comment]
I agree and would prefer that to be in `ports-of-call` only reason it's currently in spiner is we didn't see a way to write it in a "spiner-agnostic" way when we wrote it. Very much open to suggestions. :)
